FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl gnupg git \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY backend/requirements.txt ./backend/
COPY frontend/package.json ./frontend/

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install --no-cache-dir -r backend/requirements.txt

RUN cd frontend && npm install

CMD ["sleep", "infinity"]
